arrowParens: avoid
bracketSameLine: false
bracketSpacing: true
embeddedLanguageFormatting: auto
endOfLine: lf
htmlWhitespaceSensitivity: css
jsxSingleQuote: false
printWidth: 80
proseWrap: always
quoteProps: as-needed
semi: false
singleQuote: false
tabWidth: 4
tabs: false
trailingComma: es5